exports.Countries = function() {
    return [ { name: 'Afghanistan ',
    isoCode: 'AF',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Albania ',
    isoCode: 'AL',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Algeria ',
    isoCode: 'DZ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Argentina ',
    isoCode: 'AR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Armenia ',
    isoCode: 'AM',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Australia|Australia ',
    isoCode: 'AU',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false },
  { name: 'Austria ',
    isoCode: 'AT',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Azerbaijan ',
    isoCode: 'AZ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Bahrain ',
    isoCode: 'BH',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Bangladesh ',
    isoCode: 'BD',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Barbados ',
    isoCode: 'BB',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Belarus ',
    isoCode: 'BY',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Belgium|Belgium ',
    isoCode: 'BE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Belize ',
    isoCode: 'BZ',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false },
  { name: 'Bolivia ',
    isoCode: 'BO',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Bosnia and Herzegovina ',
    isoCode: 'BA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Brazil|Brazil ',
    isoCode: 'BR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Brunei ',
    isoCode: 'BN',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Bulgaria ',
    isoCode: 'BG',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Cambodia ',
    isoCode: 'KH',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Canada|Canada ',
    isoCode: 'CA',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false },
  { name: 'Cape Verde ',
    isoCode: 'CV',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Chile ',
    isoCode: 'CL',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'China|China%2C People\'s Republic of ',
    isoCode: 'CN',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Colombia|Colombia ',
    isoCode: 'CO',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Costa Rica ',
    isoCode: 'CR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Croatia ',
    isoCode: 'HR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Cyprus|Cyprus ',
    isoCode: 'CY',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'the Czech Republic|Czech Republic ',
    isoCode: 'CZ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Denmark|Denmark ',
    isoCode: 'DK',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Dominica ',
    isoCode: 'DM',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Dominican Republic ',
    isoCode: 'DM',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Ecuador ',
    isoCode: 'EC',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Egypt ',
    isoCode: 'EG',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'El Salvador ',
    isoCode: 'SV',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Estonia ',
    isoCode: 'EE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Ethiopia ',
    isoCode: 'ET',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Federated States of Micronesia ',
    isoCode: 'FM',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false },
  { name: 'Finland|Finland ',
    isoCode: 'FI',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'France|France ',
    isoCode: 'FR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Georgia (country)|Georgia ',
    isoCode: 'GE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Germany ',
    isoCode: 'DE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Greece|Greece ',
    isoCode: 'GR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Greenland ',
    isoCode: 'GL',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Grenada ',
    isoCode: 'GD',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Guatemala ',
    isoCode: 'GT',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Guyana ',
    isoCode: 'GY',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Hong Kong ',
    isoCode: 'HK',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Honduras ',
    isoCode: 'HN',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Hungary ',
    isoCode: 'HU',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Iceland ',
    isoCode: 'IS',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'India|India ',
    isoCode: 'IN',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Indonesia ',
    isoCode: 'ID',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Iran|Iran ',
    isoCode: 'IR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Iraq ',
    isoCode: 'IQ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'the Republic of Ireland|Ireland ',
    isoCode: 'IE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Israel ',
    isoCode: 'IL',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Italy ',
    isoCode: 'IT',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Jamaica ',
    isoCode: 'JM',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Japan|Japan ',
    isoCode: 'JP',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Jordan ',
    isoCode: 'JO',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Kazakhstan ',
    isoCode: 'KZ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Kenya ',
    isoCode: 'KE',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false },
  { name: 'Korea ',
    isoCode: 'KR',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Kuwait ',
    isoCode: 'KW',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Kyrgyzstan ',
    isoCode: 'KG',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Laos ',
    isoCode: 'LA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Latvia ',
    isoCode: 'LV',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Lebanon ',
    isoCode: 'LB',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Libya ',
    isoCode: 'LY',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Liechtenstein ',
    isoCode: 'LI',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Lithuania ',
    isoCode: 'LT',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Luxembourg ',
    isoCode: 'LU',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Macau ',
    isoCode: 'MO',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Republic of Macedonia|Macedonia ',
    isoCode: 'MK',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Malaysia ',
    isoCode: 'MY',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Maldives ',
    isoCode: 'MV',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Malta ',
    isoCode: 'MT',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Moldova ',
    isoCode: 'MD',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Mexico ',
    isoCode: 'MX',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Monaco ',
    isoCode: 'MC',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Mongolia ',
    isoCode: 'MN',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Montenegro ',
    isoCode: 'ME',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Morocco ',
    isoCode: 'MA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Myanmar ',
    isoCode: 'MM',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Namibia ',
    isoCode: 'NA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Nepal ',
    isoCode: 'NP',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'the Netherlands|Netherlands ',
    isoCode: 'NL',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'New Zealand ',
    isoCode: 'NZ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Nicaragua ',
    isoCode: 'NI',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Nigeria ',
    isoCode: 'NE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Norway|Norway ',
    isoCode: 'NO',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Oman ',
    isoCode: 'OM',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Pakistan ',
    isoCode: 'PK',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Palau ',
    isoCode: 'PW',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Panama ',
    isoCode: 'PA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Paraguay ',
    isoCode: 'PY',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Peru ',
    isoCode: 'PE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'the Philippines|Philippines ',
    isoCode: 'PH',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false },
  { name: 'Poland|Poland ',
    isoCode: 'PL',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Portugal ',
    isoCode: 'PT',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Qatar ',
    isoCode: 'QA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Romania ',
    isoCode: 'RO',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Russia ',
    isoCode: 'RU',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Saint Kitts and Nevis ',
    isoCode: 'KN',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Saint Lucia ',
    isoCode: 'LC',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Saint Vincent and the Grenadines ',
    isoCode: 'VC',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Saudi Arabia ',
    isoCode: 'SA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Serbia|Serbia ',
    isoCode: 'RS',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Singapore ',
    isoCode: 'SG',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Slovakia ',
    isoCode: 'SK',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Slovenia ',
    isoCode: 'SI',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'South Africa|South Africa ',
    isoCode: 'ZA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Spain|Spain ',
    isoCode: 'ES',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Sri Lanka ',
    isoCode: 'LK',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Sudan ',
    isoCode: 'SD',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Suriname ',
    isoCode: 'SR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Sweden|Sweden ',
    isoCode: 'SE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Switzerland ',
    isoCode: 'CH',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Syria ',
    isoCode: 'SY',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Taiwan%2C Republic of China ',
    isoCode: 'TW',
    dateFormat: 'YYYY/MM/DD',
    dateMonthFirst: false },
  { name: 'Tajikistan ',
    isoCode: 'TJ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Thailand|Thailand ',
    isoCode: 'TH',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Trinidad and Tobago ',
    isoCode: 'TT',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Tunisia ',
    isoCode: 'TN',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Turkey|Turkey ',
    isoCode: 'TR',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Turkmenistan ',
    isoCode: 'TM',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Ukraine ',
    isoCode: 'UA',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'United Arab Emirates ',
    isoCode: 'AE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'the United Kingdom|United Kingdom ',
    isoCode: 'GB',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'the United States|United States of America ',
    isoCode: 'US',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false },
  { name: 'Uzbekistan ',
    isoCode: 'UZ',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Venezuela ',
    isoCode: 'VE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Vietnam ',
    isoCode: 'VN',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Yemen ',
    isoCode: 'YE',
    dateFormat: 'DD/MM/YYYY',
    dateMonthFirst: false },
  { name: 'Zimbabwe ',
    isoCode: 'ZW',
    dateFormat: 'MM/DD/YYYY',
    dateMonthFirst: false } ]

;
}